name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: RTL Linting
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Verilator and dos2unix
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator dos2unix

      - name: Run Verilator Lint
        # Override VERILATOR_BIN and fix Windows CRLF line endings
        run: |
          dos2unix filelist.f Makefile
          make lint VERILATOR_BIN=verilator
